package com.hotmail.or_dvir.tracks.models

import com.hotmail.or_dvir.tracks.millisToLocalDateTime
import com.hotmail.or_dvir.tracks.toUserFriendlyText

data class EventOccurrence(
    val startMillis: Long,
    val endMillis: Long?,
    val note: String?,
    // generated by room
    val id: Int = 0,
    // generated by room
    val eventId: Int
) {
    val startTimeUserFriendly: String = startMillis.millisToLocalDateTime().toUserFriendlyText()
    val endTimeUserFriendly = endMillis?.millisToLocalDateTime()?.toUserFriendlyText()
}
