package com.hotmail.or_dvir.tracks.models

import java.io.Serializable

data class TrackedEvent(
    val name: String,
    // generated by room
    val id: Int = 0
) : Serializable
// serialization is required for the Voyager navigation library because this is passed
// as a screen parameter
