package com.hotmail.or_dvir.tracks.models

data class TrackedEventInstance(
    val startMillis: Long,
    val endMillis: Long?,
    val note: String?,
    // generated by room
    val id: Int = 0,
    // generated by room
    val eventId: Int
)
